- name  : Demo on using variables on playbooks
  hosts : all
  vars  :                                          # Global variables  : Variables can be accessed by all the tasks of the play
    URL : play.google.com
  tasks :
    - name : Printing value of the variable
      ansible.builtin.debug:
        msg : value of URL is {{ URL }}

    - name : Demo to show local variables
      ansible.builtin.debug:
        msg : value of URL is {{ URL }}
      vars :                                       # Local Variables : 
         URL : task.google.com

    - name : Demo to show quotes
      ansible.builtin.debug:
        msg : "{{ URL }}" 