# Demo on facts

- name : Demo on using conditions
  hosts : all
  tasks :
    - name : Run this task only when the distribution is centOS
      ansible.builtin.debug:
        msg : I am a centOS machine
      when: ansible_distribution == "Debian"
        
    - name : Run this task only when the distribution is debian machine
      ansible.builtin.debug:
        msg :  I am a Debian machine