# Demo on facts

- name : Demo on using facts
  hosts : all
  tasks :
    - name : Printing the fact
      ansible.builtin.debug:
        msg : ansible_distribution is {{ ansible_distribution }}
    - name : Printing the mac address of the machine
      ansible.builtin.debug:
        msg :  macaddress is {{ ansible_default_ipv4.macaddress }}